# Generated by Django 2.0.2 on 2018-02-28 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id_author', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id_link', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id_post', models.AutoField(primary_key=True, serialize=False)),
                ('post', models.TextField()),
                ('id_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='go.Authors')),
                ('id_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='go.Links')),
            ],
        ),
    ]
