# Generated by Django 2.0.2 on 2018-03-03 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0002_auto_20180228_1406'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Posts',
        ),
    ]
