# Generated by Django 2.0.2 on 2018-03-03 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0003_auto_20180303_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='id_link',
        ),
        migrations.AddField(
            model_name='posts',
            name='link',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Links',
        ),
    ]
